# Generated by Django 3.2.16 on 2023-01-04 10:58

import django.contrib.postgres.fields
from django.db import migrations, models
import pred_models.models


class Migration(migrations.Migration):

    dependencies = [
        ('pred_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmodel',
            name='classification_report',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='predmodel',
            name='confusion_matrix',
            field=models.ImageField(null=True, upload_to=pred_models.models.get_folder_path),
        ),
        migrations.AddField(
            model_name='predmodel',
            name='feature_importance_plot',
            field=models.ImageField(null=True, upload_to=pred_models.models.get_folder_path),
        ),
        migrations.AddField(
            model_name='predmodel',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), null=True, size=None),
        ),
        migrations.AddField(
            model_name='predmodel',
            name='prc_plot',
            field=models.ImageField(null=True, upload_to=pred_models.models.get_folder_path),
        ),
        migrations.AddField(
            model_name='predmodel',
            name='roc_plot',
            field=models.ImageField(null=True, upload_to=pred_models.models.get_folder_path),
        ),
        migrations.AlterField(
            model_name='predmodel',
            name='test_set',
            field=models.FileField(upload_to=pred_models.models.get_folder_path),
        ),
        migrations.AlterField(
            model_name='predmodel',
            name='train_set',
            field=models.FileField(upload_to=pred_models.models.get_folder_path),
        ),
        migrations.AlterField(
            model_name='predmodel',
            name='trained_model',
            field=models.FileField(upload_to=pred_models.models.get_folder_path),
        ),
    ]
